### ISSUE TITLE
IpcReactorUnitTests failing on travis

### ISSUE THREAD

**Issue by skyfrench** [odin-detector/odin-data#216] opened 2019-09-02 10:06 UTC
```
Leaving test suite "IpcMessageUnitTest"
Entering test suite "IpcReactorUnitTest"
Entering test case "ReactorTimerTest"
Setup test fixture
unknown location(0): fatal error in "ReactorTimerTest": std::exception: Invalid argument
Leaving test case "ReactorTimerTest"; testing time: 425mks
Entering test case "ReactorChannelTest"
Setup test fixture
unknown location(0): fatal error in "ReactorChannelTest": std::exception: Invalid argument
Leaving test case "ReactorChannelTest"; testing time: 209mks
Entering test case "ReactorSendFromTimerTest"
Setup test fixture
unknown location(0): fatal error in "ReactorSendFromTimerTest": std::exception: Invalid argument
```
Last successful build [#911](https://travis-ci.org/odin-detector/odin-data/builds/569343905) (boost 1.54).
Builds thereafter failing e.g. [#912](https://travis-ci.org/odin-detector/odin-data/builds/572238982) (boost 1.58)

**Comment by timcnicholls** [comment] 2019-09-03 11:14
I've built odin-data off the integration-test branch with boost 1.58.0 on CentOS 7 and there are no errors in the FR unit test app... 😬 

Will require further investigation in a VM or container that matches travis.

**Comment by timcnicholls** [comment] 2019-09-04 10:00
I've build a docker image based on Ubuntu 16.04 (Xenial), which also fails the tests in the same way. 

**BUT...**

The bigger change between builds [#911](https://travis-ci.org/odin-detector/odin-data/builds/569343905) and [#912](https://travis-ci.org/odin-detector/odin-data/builds/572238982) is that travis changed the default Ubuntu build image from 14.04 (Trusy) to 16.04 (Xenial), so lots of packages are different.

The failure appears to be in the ZMQ socket `bind()` call in the test fixture constructor rather than anywhere in boost. The exception is raised by libzmq C++ binding when the underlying bind call returns a non-zero error code and the standard socket library is giving the slightly unhelpful error message `invalid argument`.

I've debugged this and it's due to my incorrect use of `stringstream` to derive a  `const char*` random endpoint in `ReactorTestFixture`:

```
    // Construct a random endpoint name to avoid successive tests reporting address already in use
    int endpoint_id = random();
    std::stringstream ss;
    ss << "inproc://reactor_channel_" << endpoint_id;
    const char* random_endpoint = ss.str().c_str();
``` 
The problem is that `ss.str()` goes out of scope before `random_endpoint` gets used, and the `bind()` call gets an empty string for the endpoint. If I change the above code to make a temporary string first, the endpoint is correctly formed and the tests pass:
```
    const std::string& tmp_str = ss.str();
    const char* random_endpoint = tmp_str.c_str();
```
So I guess the fact this worked before was due to sheer luck with memory allocation handling by the compiler and C++ runtime in the old version leaving the memory pointed at by `random_endpoint` still containing a null-terminated string.

I'll push this commit at the `integration-test` branch.

**Closed** 2019-09-05 07:40 UTC
Labels: bug
